#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf { float16_t data[]; } buf;

void useAsAcc(coopmatHW<float16_t, 16, 16> P,
              coopmatHW<float16_t, 16, 16> A,
              coopmatHW<float16_t, 16, 16> B);

void produce(out coopmatHW<float16_t, 16, 16> P,
             coopmatHW<float16_t, 16, 16> A,
             coopmatHW<float16_t, 16, 16> B,
             coopmatHW<float16_t, 16, 16> C)
{
    coopMatMulAddHW(P, A, B, C);
}

void main()
{
    const ivec2 shape = ivec2(16, 16);
    const ivec2 zeroOffset = ivec2(0, 0);

    coopmatHW<float16_t, 16, 16> X, Y;
    coopmatHW<float16_t, 16, 16> A, B, C;
    coopmatHW<float16_t, 16, 16> D0, D1;

    coopMatLoadHW(X, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(Y, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(A, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(B, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(C, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);

    coopMatMulAddHW(D0, X, B, C);
    useAsAcc(X, A, B);

    coopMatMulAddHW(D1, Y, B, C);
    produce(Y, A, B, C);
}

void useAsAcc(coopmatHW<float16_t, 16, 16> P,
              coopmatHW<float16_t, 16, 16> A,
              coopmatHW<float16_t, 16, 16> B)
{
    coopmatHW<float16_t, 16, 16> D;
    coopMatMulAddHW(D, A, B, P);
}
