#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer BufA { float16_t a_data[]; } bufA;
layout(set = 0, binding = 1) buffer BufB { float16_t b_data[]; } bufB;
layout(set = 0, binding = 2) buffer BufC { float16_t c_data[]; } bufC;
layout(set = 0, binding = 3) buffer BufD { float16_t d_data[]; } bufD;

// Test 1: Normal matmuladd D = A*B + C
// A(16x8) -> MatrixUseAHW, B(8x16) -> MatrixUseBHW, C(16x16)/D -> MatrixAccumulatorHW
void main()
{
    const ivec2 shapeA = ivec2(16, 8);
    const ivec2 shapeB = ivec2(8, 16);
    const ivec2 shapeC = ivec2(16, 16);
    const ivec2 zeroOffset = ivec2(0, 0);

    coopmatHW<float16_t, 16, 8>  A;
    coopmatHW<float16_t, 8, 16>  B;
    coopmatHW<float16_t, 16, 16> C;
    coopmatHW<float16_t, 16, 16> D;

    coopMatLoadHW(A, bufA.a_data, shapeA, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(B, bufB.b_data, shapeB, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(C, bufC.c_data, shapeC, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatMulAddHW(D, A, B, C);
    coopMatStoreHW(D, bufD.d_data, shapeC, zeroOffset, gl_CooperativeMatrixLayoutColumnMajorHW);
}
