#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable
#extension GL_EXT_buffer_reference : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer MatrixBuf {
    u64vec3 matrixData[];
} matrixBuf;

layout(set = 0, binding = 0) buffer MatrixBuf2 {
    coherent float16_t matrixData[];
} matrixBuf2;

layout(set = 0, binding = 0) coherent buffer MatrixBuf3 {
    volatile float32_t matrixData[];
} matrixBuf3;

layout(set = 0, binding = 0, buffer_reference) buffer MatrixBuf4 {
    coherent float16_t matrixData[];
};

shared uint32_t matrixShmem[100];

void main()
{
    coopvecHW<float, 5> v;

    coopVecLoadHW(v, matrixBuf.matrixData, 0u);
    coopVecStoreHW(v, matrixBuf.matrixData, 0u);

    coopVecLoadHW(v, matrixBuf2.matrixData, 1u);
    coopVecStoreHW(v, matrixBuf2.matrixData, 1u);

    coopVecLoadHW(v, matrixBuf3.matrixData, 2u);
    coopVecStoreHW(v, matrixBuf3.matrixData, 2u);

    MatrixBuf4 matrixBuf4;
    coopVecLoadHW(v, matrixBuf4.matrixData, 3u);
    coopVecStoreHW(v, matrixBuf4.matrixData, 3u);

    coopVecLoadHW(v, matrixShmem, 4u);
    coopVecStoreHW(v, matrixShmem, 4u);
}
