#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf { float16_t data[]; } buf;

void main()
{
    const ivec2 shape = ivec2(16, 16);
    const ivec2 zeroOffset = ivec2(0, 0);

    coopmatHW<float16_t, 16, 16> X, Y, W;
    coopmatHW<float16_t, 16, 16> A, B, C;
    coopmatHW<float16_t, 16, 16> D0, D1, D2, D3;

    coopMatLoadHW(X, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(A, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(B, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(C, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);

    coopMatMulAddHW(D0, X, B, C);
    coopMatMulAddHW(D1, A, X, C);

    Y = X;
    coopMatMulAddHW(D2, A, B, Y);

    coopmatHW<float16_t, 16, 16> Z = X;
    coopMatMulAddHW(D3, A, B, Z);

    X = Y;
    coopMatMulAddHW(D0, X, B, C);

    W = coopmatHW<float16_t, 16, 16>(X);
    coopMatMulAddHW(D1, W, B, C);
}
