#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf { float16_t data[]; } buf;

void useAsAcc(coopmatHW<float16_t, 16, 16> P,
              coopmatHW<float16_t, 16, 16> A,
              coopmatHW<float16_t, 16, 16> B)
{
    coopmatHW<float16_t, 16, 16> D;
    coopMatMulAddHW(D, A, B, P);
}

void useAsOperand(coopmatHW<float16_t, 16, 16> P,
                  coopmatHW<float16_t, 16, 16> B,
                  coopmatHW<float16_t, 16, 16> C)
{
    coopmatHW<float16_t, 16, 16> D;
    coopMatMulAddHW(D, P, B, C);
}

coopmatHW<float16_t, 16, 16> makeAcc(coopmatHW<float16_t, 16, 16> A,
                                       coopmatHW<float16_t, 16, 16> B,
                                       coopmatHW<float16_t, 16, 16> C)
{
    coopmatHW<float16_t, 16, 16> D;
    coopMatMulAddHW(D, A, B, C);
    return D;
}

void main()
{
    const ivec2 shape = ivec2(16, 16);
    const ivec2 zeroOffset = ivec2(0, 0);
    bool cond = gl_LocalInvocationID.x == 0u;

    coopmatHW<float16_t, 16, 16> X, Y;
    coopmatHW<float16_t, 16, 16> A, B, C;
    coopmatHW<float16_t, 16, 16> D0, D1, D2, D3;

    coopMatLoadHW(X, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(Y, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(A, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(B, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(C, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);

    if (cond) {
        coopMatMulAddHW(D0, X, B, C);
    } else {
        coopMatMulAddHW(D1, A, X, C);
    }

    {
        coopmatHW<float16_t, 16, 16> X;
        coopMatLoadHW(X, buf.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
        coopMatMulAddHW(D2, A, B, X);
    }

    Y = X;
    useAsAcc(Y, A, B);
    useAsOperand(X, B, C);

    coopmatHW<float16_t, 16, 16> R = makeAcc(A, B, C);
    coopMatMulAddHW(D3, R, B, C);
}
