#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_HW_neural_shader : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(scalar, set = 0, binding = 0) buffer InMatABlock {
    uint8_t x[];
} inMatA;

layout(scalar, set = 0, binding = 1) buffer InMatBBlock {
    uint8_t x[];
} inMatB;

layout(scalar, set = 0, binding = 2) buffer InMatCBlock {
    uint32_t x[];
} inMatC;

layout(scalar, set = 0, binding = 3) buffer OutMatBlock {
    uint32_t x[];
} outMat;

void main()
{
    coopmatHW<uint8_t, 16, 32> matA;
    coopMatLoadHW(matA, inMatA.x, ivec2(16, 32), ivec2(0, 0), 0);

    coopmatHW<uint8_t, 32, 16> matB;
    coopMatLoadHW(matB, inMatB.x, ivec2(32, 16), ivec2(0, 0), 1);

    coopmatHW<uint32_t, 16, 16> matC;
    coopMatLoadHW(matC, inMatC.x, ivec2(16, 16), ivec2(0, 0), 0);

    coopmatHW<uint32_t, 16, 16> matD;
    coopMatMulAddHW(matD, matA, matB, matC);

    coopmatHW<uint8_t, 16, 16> matE = coopmatHW<uint8_t, 16, 16>(matD);
    coopmatHW<uint32_t, 32, 16> matF;

    coopMatMulHW(matF, matB, matE);
    coopMatStoreHW(matF, outMat.x, ivec2(32, 16), ivec2(0, 0), 0);
}
