#version 450
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_NV_gpu_shader5)
#extension GL_NV_gpu_shader5 : require
#else
#error No extension available for FP16.
#endif
#extension GL_HW_neural_shader : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer Buf
{
    float16_t data[];
} buf;

void useAsAcc(coopmatHW<float16_t, 16u, 16u> P, coopmatHW<float16_t, 16u, 16u> A, coopmatHW<float16_t, 16u, 16u> B)
{
    coopmatHW<float16_t, 16u, 16u> _112;
    coopMatMulAddHW(_112, A, coopmatHW<float16_t, 16u, 16u>(B), coopmatHW<float16_t, 16u, 16u>(P));
    coopmatHW<float16_t, 16u, 16u> tempArg = _112;
    coopmatHW<float16_t, 16u, 16u> D = tempArg;
}

void produce(out coopmatHW<float16_t, 16u, 16u> P, coopmatHW<float16_t, 16u, 16u> A, coopmatHW<float16_t, 16u, 16u> B, coopmatHW<float16_t, 16u, 16u> C)
{
    coopmatHW<float16_t, 16u, 16u> _33;
    coopMatMulAddHW(_33, A, coopmatHW<float16_t, 16u, 16u>(B), coopmatHW<float16_t, 16u, 16u>(C));
    coopmatHW<float16_t, 16u, 16u> tempArg = _33;
    P = coopmatHW<float16_t, 16u, 16u>(tempArg);
}

void main()
{
    coopmatHW<float16_t, 16u, 16u> _49;
    coopMatLoadHW(_49, buf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg = _49;
    coopmatHW<float16_t, 16u, 16u> X = tempArg;
    coopmatHW<float16_t, 16u, 16u> _54;
    coopMatLoadHW(_54, buf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg_1 = _54;
    coopmatHW<float16_t, 16u, 16u> Y = tempArg_1;
    coopmatHW<float16_t, 16u, 16u> _59;
    coopMatLoadHW(_59, buf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg_2 = _59;
    coopmatHW<float16_t, 16u, 16u> A = tempArg_2;
    coopmatHW<float16_t, 16u, 16u> _65;
    coopMatLoadHW(_65, buf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg_3 = _65;
    coopmatHW<float16_t, 16u, 16u> B = tempArg_3;
    coopmatHW<float16_t, 16u, 16u> _70;
    coopMatLoadHW(_70, buf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg_4 = _70;
    coopmatHW<float16_t, 16u, 16u> C = tempArg_4;
    coopmatHW<float16_t, 16u, 16u> _77;
    coopMatMulAddHW(_77, X, B, C);
    coopmatHW<float16_t, 16u, 16u> tempArg_5 = _77;
    coopmatHW<float16_t, 16u, 16u> D0 = tempArg_5;
    coopmatHW<float16_t, 16u, 16u> param = X;
    coopmatHW<float16_t, 16u, 16u> param_1 = A;
    coopmatHW<float16_t, 16u, 16u> param_2 = coopmatHW<float16_t, 16u, 16u>(B);
    useAsAcc(param, param_1, param_2);
    coopmatHW<float16_t, 16u, 16u> _92;
    coopMatMulAddHW(_92, Y, B, C);
    coopmatHW<float16_t, 16u, 16u> tempArg_6 = _92;
    coopmatHW<float16_t, 16u, 16u> D1 = tempArg_6;
    coopmatHW<float16_t, 16u, 16u> param_4 = A;
    coopmatHW<float16_t, 16u, 16u> param_5 = coopmatHW<float16_t, 16u, 16u>(B);
    coopmatHW<float16_t, 16u, 16u> param_6 = coopmatHW<float16_t, 16u, 16u>(C);
    coopmatHW<float16_t, 16u, 16u> param_3;
    produce(param_3, param_4, param_5, param_6);
    Y = param_3;
}

