#version 450
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_NV_gpu_shader5)
#extension GL_NV_gpu_shader5 : require
#else
#error No extension available for FP16.
#endif
#extension GL_HW_neural_shader : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer InBuf
{
    float16_t data[];
} inBuf;

layout(binding = 1, std430) buffer OutBuf
{
    float16_t data[];
} outBuf;

void main()
{
    coopmatHW<float16_t, 16u, 16u> _24;
    coopMatLoadHW(_24, inBuf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg = _24;
    coopmatHW<float16_t, 16u, 16u> value = tempArg;
    coopMatStoreHW(value, outBuf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutColumnMajorHW);
}

