#version 450
#if defined(GL_AMD_gpu_shader_half_float)
#extension GL_AMD_gpu_shader_half_float : require
#elif defined(GL_NV_gpu_shader5)
#extension GL_NV_gpu_shader5 : require
#else
#error No extension available for FP16.
#endif
#extension GL_HW_neural_shader : require
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0, std430) buffer Buf
{
    float16_t data[];
} buf;

void doVecMul(coopmatHW<float16_t, 16u, 16u> mat, coopvecHW<float16_t, 16u> vin)
{
    coopvecHW<float16_t, 16u> _29;
    coopVecMatMulHW(_29, vin, coopmatHW<float16_t, 16u, 16u>(mat));
    coopvecHW<float16_t, 16u> tempArg = _29;
    coopvecHW<float16_t, 16u> result = tempArg;
}

void doVecMulAdd(coopmatHW<float16_t, 16u, 16u> mat, coopvecHW<float16_t, 16u> vin, coopvecHW<float16_t, 16u> bias)
{
    coopvecHW<float16_t, 16u> _36;
    coopVecMatMulHW(_36, vin, coopmatHW<float16_t, 16u, 16u>(mat));
    coopvecHW<float16_t, 16u> tempArg = _36;
    coopvecHW<float16_t, 16u> r1 = tempArg;
    coopvecHW<float16_t, 16u> _44;
    coopVecMatMulAddHW(_44, vin, coopmatHW<float16_t, 16u, 16u>(mat), bias);
    coopvecHW<float16_t, 16u> tempArg_1 = _44;
    coopvecHW<float16_t, 16u> r2 = tempArg_1;
}

void main()
{
    coopmatHW<float16_t, 16u, 16u> _60;
    coopMatLoadHW(_60, buf.data, ivec2(16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopmatHW<float16_t, 16u, 16u> tempArg = _60;
    coopmatHW<float16_t, 16u, 16u> M = tempArg;
    coopmatHW<float16_t, 16u, 16u> param = M;
    coopvecHW<float16_t, 16u> v0;
    coopvecHW<float16_t, 16u> param_1 = v0;
    doVecMul(param, param_1);
    coopmatHW<float16_t, 16u, 16u> param_2 = M;
    coopvecHW<float16_t, 16u> param_3 = v0;
    coopvecHW<float16_t, 16u> bias;
    coopvecHW<float16_t, 16u> param_4 = bias;
    doVecMulAdd(param_2, param_3, param_4);
}

